# -*- coding: utf-8 -*-
"""GradedCHAIDDecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEHU79qgJv9SFGFY3gIlmgK_2U5RNz3-
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import drive
drive.mount('/content/gdrive')

from google.colab import files
uploaded = files.upload()

data = pd.read_csv("datasetcsv.csv");
data.head()

!pip install chefboost

from chefboost import Chefboost as cb

configureAlgo = {"algorithm" : "CHAID"}
decision_tree = cb.fit(data, configureAlgo)

test_data = data.iloc[2]
test_data

cb.predict(decision_tree, test_data)
output: 'Yes'

def findDecision(obj):
  if obj[0] == 'rainy':
    if obj[3] == 'weak':
      return 'no'
    elif obj[3] == 'strong':
      return 'no'
    else:
      return 'no'
  
  elif obj[0] == 'sunny':
    if obj[2] == 'high':
      return 'no'
    elif obj[2] == 'normal':
      return 'yes'
    else:
      return 'yes'

  elif obj[0] == 'overcast':
    return 'yes'
  else:
    return 'yes'

findDecision(test_data)